import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { motion } from "framer-motion"
import Link from 'next/link'
import Box from '@/components/Box'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Framer Motion and Intersection Observer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Link href="about">
            <motion.span
                animate={{
                    backgroundColor: ["#ff0000", "rgba(0,0,0,0)", "#00ff00"]
                }}
                transition={{
                    duration: 2,
                    repeat: Infinity,
                    repeatType: "reverse"
                }}
            >
                About Page
            </motion.span>
        </Link>
        <Box num={1}/>
        <Box num={2}/>
        <Box num={3}/>
        <Box num={4}/>
        <Box num={5}/>
        <Box num={6}/>
      </main>
    </>
  )
}
